server:
  port: 81

spring:
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
#  datasource:
#      url: jdbc:mysql://192.168.233.132:3306/reptile?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
#      username: root
#      password: 1234
#      driver-class-name: com.mysql.jdbc.Driver
#      # 使用druid数据源
#      type: com.alibaba.druid.pool.DruidDataSource
#      druid:
#        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#        filters: stat,slf4j,config
#        connection-properties: stat.mergeSql=true;stat.slowSqlMillis=5000;
  application:
    name: register-web
  freemarker:
    request-context-attribute: req  #req访问request
    suffix: .ftl  #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置
#    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
        number_format: '0.##'   #数字格式化，无小数点
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
#pagehelper:
#  helper-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql
#mapper:
#  not-empty: true
#  mappers: com.reptile.mapper.MyMapper
#  identity: MYSQL
#mybatis:
#  mapper-locations: classpath*:mapper/**/*.xml
#  configuration:
#    map-underscore-to-camel-case: true

#logging:
#  path: logs/
